---
version: "2.0"

services:
  dapp:
    image: mdaeva/starbound-client-testnet:1.0.4
    command: docker run -p 4000:4000 mdaeva/starbound-client-testnet:1.0.4 <enc_key>
    expose:
      - port: 4000
        as: 443
        accept:
          - starbound.fun
        to:
          - global: true

profiles:
  compute:
    dapp:
      resources:
        cpu:
          units: 1
        memory:
          size: 512M
        storage:
          size: 3G
  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        dapp:
          denom: uakt
          amount: 2000

deployment:
  dapp:
    dcloud:
      profile: dapp
      count: 1