/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, Uint128, Addr, Decimal, Timestamp, Uint64, Asset, Pool, User, TransferParams, QueryMsg, MigrateMsg, Config, Ledger, QueryPoolsAndUsersResponse } from "./StarboundOsmosis.types";
export interface StarboundOsmosisMessage {
  contractAddress: string;
  sender: string;
  deposit: ({
    assetList,
    dayCounter,
    isRebalancingUsed
  }: {
    assetList: Asset[];
    dayCounter: Uint128;
    isRebalancingUsed: boolean;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  withdraw: ({
    amount
  }: {
    amount: Uint128;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateConfig: ({
    dappAddressAndDenomList,
    feeDefault,
    feeOsmo,
    scheduler,
    stablecoinDenom,
    stablecoinPoolId
  }: {
    dappAddressAndDenomList?: string[][][];
    feeDefault?: Decimal;
    feeOsmo?: Decimal;
    scheduler?: string;
    stablecoinDenom?: string;
    stablecoinPoolId?: number;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updatePoolsAndUsers: ({
    pools,
    users
  }: {
    pools: string[][];
    users: string[][];
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  swap: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
  transfer: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
  multiTransfer: ({
    params
  }: {
    params: TransferParams[];
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class StarboundOsmosisMessageComposer implements StarboundOsmosisMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.deposit = this.deposit.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.updatePoolsAndUsers = this.updatePoolsAndUsers.bind(this);
    this.swap = this.swap.bind(this);
    this.transfer = this.transfer.bind(this);
    this.multiTransfer = this.multiTransfer.bind(this);
  }

  deposit = ({
    assetList,
    dayCounter,
    isRebalancingUsed
  }: {
    assetList: Asset[];
    dayCounter: Uint128;
    isRebalancingUsed: boolean;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit: {
            asset_list: assetList,
            day_counter: dayCounter,
            is_rebalancing_used: isRebalancingUsed
          }
        })),
        funds
      })
    };
  };
  withdraw = ({
    amount
  }: {
    amount: Uint128;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw: {
            amount
          }
        })),
        funds
      })
    };
  };
  updateConfig = ({
    dappAddressAndDenomList,
    feeDefault,
    feeOsmo,
    scheduler,
    stablecoinDenom,
    stablecoinPoolId
  }: {
    dappAddressAndDenomList?: string[][][];
    feeDefault?: Decimal;
    feeOsmo?: Decimal;
    scheduler?: string;
    stablecoinDenom?: string;
    stablecoinPoolId?: number;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            dapp_address_and_denom_list: dappAddressAndDenomList,
            fee_default: feeDefault,
            fee_osmo: feeOsmo,
            scheduler,
            stablecoin_denom: stablecoinDenom,
            stablecoin_pool_id: stablecoinPoolId
          }
        })),
        funds
      })
    };
  };
  updatePoolsAndUsers = ({
    pools,
    users
  }: {
    pools: string[][];
    users: string[][];
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_pools_and_users: {
            pools,
            users
          }
        })),
        funds
      })
    };
  };
  swap = (funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          swap: {}
        })),
        funds
      })
    };
  };
  transfer = (funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          transfer: {}
        })),
        funds
      })
    };
  };
  multiTransfer = ({
    params
  }: {
    params: TransferParams[];
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          multi_transfer: {
            params
          }
        })),
        funds
      })
    };
  };
}