/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  deposit: {
    user: User;
  };
} | {
  withdraw: {
    amount: number;
  };
} | {
  update_scheduler: {
    address: string;
  };
} | {
  update_pools_and_users: {
    pools: PoolExtracted[];
    users: UserExtracted[];
  };
} | {
  swap: {};
} | {
  transfer: {};
} | {
  multi_transfer: {
    params: TransferParams[];
  };
};
export type Uint128 = string;
export type Addr = string;
export type Decimal = string;
export interface User {
  asset_list: Asset[];
  day_counter: Uint128;
  deposited_on_current_period: Uint128;
  deposited_on_next_period: Uint128;
  is_controlled_rebalancing: boolean;
}
export interface Asset {
  amount_to_send_until_next_epoch: Uint128;
  asset_denom: string;
  wallet_address: Addr;
  wallet_balance: Uint128;
  weight: Decimal;
}
export interface PoolExtracted {
  channel_id: string;
  denom: string;
  id: number;
  port_id: string;
  price: Decimal;
  symbol: string;
}
export interface UserExtracted {
  asset_list: AssetExtracted[];
  osmo_address: string;
}
export interface AssetExtracted {
  asset_denom: string;
  wallet_address: string;
  wallet_balance: number;
}
export interface TransferParams {
  amount: number;
  block_height: number;
  block_revision: number;
  channel_id: string;
  denom: string;
  to: string;
}
export type QueryMsg = {
  query_assets: {
    address: string;
  };
} | {
  query_pools_and_users: {};
} | {
  debug_query_pools_and_users: {};
} | {
  debug_query_bank: {};
};
export type MigrateMsg = string;
export interface DebugQueryBankResponse {
  dapp_wallet: Coin[];
  global_delta_balance_list: number[];
  global_delta_cost_list: number[];
  global_denom_list: string[];
  global_price_list: Decimal[];
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface DebugQueryPoolsAndUsersResponse {
  pools: PoolExtracted[];
  users: User[];
}
export interface QueryAssetsResponse {
  asset_list: Asset[];
}
export interface QueryPoolsAndUsersResponse {
  pools: PoolExtracted[];
  users: UserExtracted[];
}