/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  deposit: {
    asset_list?: [string, Decimal][] | null;
    down_counter?: Uint128 | null;
    is_rebalancing_used?: boolean | null;
  };
};
export type Decimal = string;
export type Uint128 = string;
export type QueryMsg = {
  query_users: {
    address_list: string[];
  };
} | {
  query_config: {};
};
export type MigrateMsg = string;
export type Addr = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Config {
  admin: Addr;
  chain_id_dev: string;
  fee_rate: Decimal;
  scheduler: Addr;
  timestamp: Timestamp;
}
export interface User {
  asset_list: Asset[];
  down_counter: Uint128;
  is_rebalancing_used: boolean;
  stable_balance: Uint128;
}
export interface Asset {
  contract: Addr;
  weight: Decimal;
}